#!/bin/bash

HOST='136.243.103.110';
USER='viptunnelvpn_ownT';
PASS='dx8qLn2WOqz7';
DB='viptunnelvpn_ownT';

service=$1
ip=$(ip route get 8.8.8.8 | awk '/src/ {f=NR} f&&NR-1==f' RS=" ")


# Full paths to binaries
NEOFETCH="/usr/bin/neofetch"
VNSTAT="/usr/bin/vnstat"

# Check if binaries exist
if [ ! -x "$NEOFETCH" ] || [ ! -x "$VNSTAT" ]; then
    echo "Error: neofetch or vnstat not found. Make sure they are installed and in your PATH."
    exit 1
fi

# Get system information
os="$($NEOFETCH os)"; os="${os##*: }"
distro="$($NEOFETCH distro)"; distro="${distro##*: }"
cpu="$($NEOFETCH cpu --cpu_speed on --cpu_cores off)"; cpu="${cpu##*: }"
memory="$($NEOFETCH memory)"; memory="${memory##*: }"
disk="$($NEOFETCH disk)"; disk="${disk##*: }"
uptime="$($NEOFETCH uptime)"; uptime="${uptime##*: }"
bandwidth="$($VNSTAT --oneline | cut -d ";" -f 15)"

  


tcpovpn=$(systemctl is-active openvpn@server.service)
udpovpn=$(systemctl is-active openvpn@server.service)
udphysteria=$(systemctl is-active openvpn@server.service)
squid=$(systemctl is-active openvpn@server.service)
ssl=$(systemctl is-active openvpn@server.service)
socket=$(systemctl is-active openvpn@server.service)
tcpusers=$(sed -n -e '/^ROUTING_TABLE/p' /etc/openvpn/server/tcpclient.log | wc -l)
udpusers=$(sed -n -e '/^ROUTING_TABLE/p' /etc/openvpn/server/tcpclient.log | wc -l)
totalovpn=$((tcpusers + udpusers))
total_hysteria=$(sed -n -e '/^ROUTING_TABLE/p' /etc/openvpn/server/tcpclient.log | wc -l)


output=$(cat <<EOF
{
 "service": "openvpn protocol",
 "ip": "$ip",
 "users": "$totalovpn",
 "bandwidth": "$bandwidth",
 "os": "$os",
 "distro": "$distro",
 "cpu": "$cpu",
 "memory": "$memory",
 "disk": "$disk",
 "uptime": "$uptime",
 "udp_hysteria": "$hysteria_port - $udphysteria",
 "tcp_port": "$tcp_port - $tcpovpn",
 "udp_port": "$udp_port - $udpovpn",
 "socket_port": "$socket_port - $socket",
 "squid_port": "$squid_port - $squid",
 "tcp_ssl_port": "$tcp_ssl_port - $ssl",
 "udp_ssl_port": "$udp_ssl_port - $ssl"
}
EOF
)

mysql -u $USER -p$PASS -D $DB -h $HOST -e "UPDATE server_list SET cpu_model='$cpu', distro='$distro', memory='$memory', uptime='$uptime', disk='$disk', bandwidth='$bandwidth', os='$os', proto='$service', tcpssl='$tcp_ssl_port', udpssl='$udp_ssl_port', tcp_status='$tcpovpn', hysteria_status='$udphysteria', udp_status='$udpovpn', ssl_status='$ssl', squid_status='$squid', socket_status='$socket', tcp='$tcp_port', udp='$udp_port', hysteria_port='$hysteria_port', squid='$squid_port', socket='$socket_port', online='$tcpusers', hysteria_online='$total_hysteria' WHERE server_ip='$ip' "



  
  
elif [[ $service == "reboot" ]];
then
sudo shutdown -r now
fi
